### ISSUE TITLE
Trying to get command-specifc help for effects/status throws a 500 error

### ISSUE THREAD

**Issue by Djelibeybi** [delfick/photons-interactor#7]
If you send the following payload to Photons:

```
{
    "command": "help",
    "args": {
        "command": "effects/status"
    }
}
```

The following error is thrown:

```
2020-03-10 09:23:39,241 ERROR   whirlwind.request_handlers.base expected string or bytes-like object
Traceback (most recent call last):
  File "/project/.photons-interactor/lib/python3.8/site-packages/whirlwind/request_handlers/base.py", line 220, in put
    info["result"] = await self.do_put(*args, **kwargs)
  File "/project/.photons-interactor/lib/python3.8/site-packages/whirlwind/request_handlers/command.py", line 80, in do_put
    return await self.commander.executor(progress_cb, self).execute(path, j)
  File "/project/.photons-interactor/lib/python3.8/site-packages/whirlwind/commander.py", line 89, in execute
    return await command.execute()
  File "/project/photons_interactor/commander/commands/base.py", line 30, in execute
    doc = dedent(getattr(kls, "__help__", kls.__doc__))
  File "/usr/local/lib/python3.8/textwrap.py", line 430, in dedent
    text = _whitespace_only_re.sub('', text)
TypeError: expected string or bytes-like object
```

**Comment by delfick** [comment]
oops, I'm missing a docstring on the StatusEffectCommand class

**Comment by delfick** [comment]
I'll fix it later

**Comment by delfick** [comment]
i.e. something like https://github.com/delfick/photons-interactor/blob/master/photons_interactor/commander/commands/effects.py#L51 for https://github.com/delfick/photons-interactor/blob/master/photons_interactor/commander/commands/effects.py#L155
